### ISSUE TITLE
Content-Type Header Handling

### ISSUE THREAD

**Issue by SProst** [cjihrig/grpc-server-js#2]
> If Content-Type does not begin with "application/grpc", gRPC servers SHOULD respond with HTTP status of 415 (Unsupported Media Type). This will prevent other HTTP/2 clients from interpreting a gRPC error response, which uses status 200 (OK), as successful.

In the headers / metadata parsing function receiveMetadata in the server-call class it might be a good idea to check this header and issue a 415 response if the header doesn't comply per the protocol.

**Comment by cjihrig** [comment]
Thanks for finding these missing edge cases.
